on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main
    workflow_dispatch:

jobs:
  hello:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello wordls"
        shell: powershell

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: powershell